// Code generated by MCHP Chatbot
/*
© [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip
    software and any derivatives exclusively with Microchip products.
    You are responsible for complying with 3rd party license terms
    applicable to your use of 3rd party software (including open source
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.?
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR
    THIS SOFTWARE.
*/
#include <stdint.h>
#include <xc.h>
#include "mcc_generated_files/X2Cscope/X2Cscope.h"
#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/timer/tmr1.h"
#include "mcc_generated_files/system/pins.h"
#include "mcc_generated_files/pwm/sccp1.h"
#include "mcc_generated_files/pwm/sccp2.h"
#include "mcc_generated_files/pwm/sccp3.h"
#include "mcc_generated_files/pwm/sccp4.h"


typedef struct {
    uint16_t cnt;
    uint16_t adc1;
    uint16_t adc2;
    uint16_t adc3;
    uint16_t adc4;
    uint16_t adc5;
    uint16_t dpi0;
    uint16_t dpi1;
    uint16_t dpi2;
    uint16_t dpi3;
    uint16_t SW0;
    uint16_t dpo0;
    uint16_t dpo1;
    uint16_t dpo2;
    uint16_t dpo3;
    uint16_t pwm_dc0;
    uint16_t pwm_dc1;
    uint16_t pwm_dc2;
    uint16_t pwm_dc3;
    uint16_t pwm_f0;
    uint16_t pwm_f1;
    uint16_t pwm_f2;
    uint16_t pwm_f3;
} MLABCURIOSITY_t;

MLABCURIOSITY_t mLabCuriosity;






static void TMR1_Callback(void)
{
    LED0_SetHigh();

    mLabCuriosity.cnt++;
    if (mLabCuriosity.cnt == 4095) {
        mLabCuriosity.cnt = 0;
    }

    // PWM section
    PWM0_DutyCycleSet(mLabCuriosity.pwm_dc0);
    PWM1_DutyCycleSet(mLabCuriosity.pwm_dc1);
    PWM2_DutyCycleSet(mLabCuriosity.pwm_dc2);
    PWM3_DutyCycleSet(mLabCuriosity.pwm_dc3);
    PWM0_PeriodSet(mLabCuriosity.pwm_f0);
    PWM1_PeriodSet(mLabCuriosity.pwm_f1);
    PWM2_PeriodSet(mLabCuriosity.pwm_f2);
    PWM3_PeriodSet(mLabCuriosity.pwm_f3);
    
    // ADC section
    if (AD1RSTATbits.CH0RRDY) { mLabCuriosity.adc1 = (uint16_t)AD1CH0DATA; }
    if (AD2RSTATbits.CH0RRDY) { mLabCuriosity.adc2 = (uint16_t)AD2CH0DATA; }
    if (AD3RSTATbits.CH0RRDY) { mLabCuriosity.adc3 = (uint16_t)AD3CH0DATA; }
    if (AD4RSTATbits.CH0RRDY) { mLabCuriosity.adc4 = (uint16_t)AD4CH0DATA; }
    if (AD5RSTATbits.CH0RRDY) { mLabCuriosity.adc5 = (uint16_t)AD5CH0DATA; }
    AD1SWTRGbits.CH0TRG = 1;
    AD2SWTRGbits.CH0TRG = 1;
    AD3SWTRGbits.CH0TRG = 1;
    AD4SWTRGbits.CH0TRG = 1;

    // GPI section
    mLabCuriosity.dpi0 = DI0_GetValue();
    mLabCuriosity.dpi1 = DI1_GetValue();
    mLabCuriosity.dpi2 = DI2_GetValue();
    mLabCuriosity.dpi3 = DI3_GetValue();
    mLabCuriosity.SW0 = SW0_GetValue();
    
    // GPO section
    if (mLabCuriosity.dpo0) { DO0_SetHigh(); } else { DO0_SetLow(); }
    if (mLabCuriosity.dpo1) { DO1_SetHigh(); } else { DO1_SetLow(); }
    if (mLabCuriosity.dpo2) { DO2_SetHigh(); } else { DO2_SetLow(); }
    if (mLabCuriosity.dpo3) { DO3_SetHigh(); } else { DO3_SetLow(); }

    
    X2Cscope_Update();
    LED0_SetLow();

}

int main(void)
{
    SYSTEM_Initialize();
    TMR1_TimeoutCallbackRegister(TMR1_Callback);

mLabCuriosity.pwm_dc0 = 1000;
mLabCuriosity.pwm_dc1 = 1000;
mLabCuriosity.pwm_dc2 = 1000;
mLabCuriosity.pwm_dc3 = 1000;
mLabCuriosity.pwm_f0 = 20000;
mLabCuriosity.pwm_f1 = 20000;
mLabCuriosity.pwm_f2 = 20000;
mLabCuriosity.pwm_f3 = 20000;

       

    while(1)
    {
        X2Cscope_Communicate();
    }
}

