// Code generated by MCHP Chatbot
/*
� [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/
#include <stdint.h>
#include <stdbool.h>
#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/timer/sccp3.h"
#include "../X2Cscope/X2Cscope.h"

/*
    X2Cscope over UART1
    - UART1 (MCC Melody): 115200 8N1, U1TX = RC10, U1RX = RC11
      -> routed to the on-board debugger virtual COM port (CDC)
    - X2Cscope_Communicate() runs in the idle loop
    - X2Cscope_Update() runs in the SCCP3 timer callback (scope sample point)

    PC side: pip install pyx2cscope ; pyx2cscope
             select the Curiosity COM port, 115200 baud and out/mLabCuriosity/default.elf
*/

/* SCCP3 clock = standard speed peripheral clock (4 MHz with the current 8 MHz FRC setup).
 * 400 counts -> 100 us -> 10 kHz scope sample rate.
 * (The MCC setting of 2 us is far too fast for an ISR on an 8 MHz CPU.) */
#define SCCP3_CLOCK_HZ          4000000UL
#define X2C_SAMPLE_PERIOD_US    100UL
#define SCCP3_PERIOD_COUNT      ((SCCP3_CLOCK_HZ / 1000000UL) * X2C_SAMPLE_PERIOD_US - 1UL)

/* Example variables - visible / writable in pyX2Cscope */
volatile uint32_t x2cTickCounter = 0;   /* incremented every sample period */
volatile uint32_t mainLoopCounter = 0;  /* incremented every idle loop pass */

// User ISR for TIMER3 (SCCP3), invoked on every timer period match
static void Timer3_UserISR(void)
{
    x2cTickCounter++;
    X2Cscope_Update();          // X2Cscope sample point (fixed rate)
}

int main(void)
{
    SYSTEM_Initialize();        // includes UART1_Initialize() and SCCP3_Timer_Initialize()

    SCCP3_Timer_Stop();
    SCCP3_Timer_PeriodSet(SCCP3_PERIOD_COUNT);
    SCCP3_Timer_TimeoutCallbackRegister(Timer3_UserISR);

    X2Cscope_Init();            // hook UART1 callbacks and init scope buffer

    SCCP3_Timer_Start();

    while(1)
    {
        mainLoopCounter++;
        X2Cscope_Communicate(); // handle LNet protocol with the pyX2Cscope GUI
    }
}
